#!/bin/bash

# Warna untuk tampilan terminal
GREEN='\033[0;32m'
NC='\033[0m'

echo -e "${GREEN}🚀 Memulai Instalasi Mikrobot STB Interaktif...${NC}"

# 1. Install Dependency System
sudo apt update && sudo apt install -y python3-pip python3-venv git

# 2. Setup Folder dan Virtual Environment
mkdir -p ~/mikrobot
cd ~/mikrobot
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

echo -e "\n${GREEN}📝 SILAKAN ISI KONFIGURASI BOT ANDA:${NC}"

# Tanya Konfigurasi Telegram
read -p "1. Masukkan Token Bot Telegram: " TOKEN
read -p "2. Masukkan Chat ID: " CHAT_ID
read -p "3. Masukkan ID Thread Utama (MikroTik): " T_UTAMA
read -p "4. Masukkan ID Thread Modem: " T_MODEM

# Tanya Konfigurasi MikroTik
read -p "5. Masukkan IP MikroTik: " MT_IP
read -p "6. Masukkan Port API MikroTik (Default 8854): " MT_PORT
MT_PORT=${MT_PORT:-8854} # Jika kosong, isi 8854
read -p "7. Masukkan Username MikroTik: " MT_USER
read -p "8. Masukkan Password MikroTik: " MT_PASS

# Tanya Konfigurasi Modem
read -p "9. Masukkan IP Modem Huawei: " MD_IP
read -p "10. Masukkan Username Telnet Modem (Default root): " MD_USER
MD_USER=${MD_USER:-root}
read -p "11. Masukkan Password Telnet Modem (Default adminhw): " MD_PASS
MD_PASS=${MD_PASS:-adminhw}

# 3. Generate file config.py secara otomatis
cat > config.py <<EOF
# --- GENERATED BY INSTALLER ---
TOKEN = '$TOKEN'
CHAT_ID = $CHAT_ID
THREAD_UTAMA = $T_UTAMA
THREAD_MODEM = $T_MODEM

MT_HOST = '$MT_IP'
MT_PORT = $MT_PORT
MT_USER = '$MT_USER'
MT_PASS = '$MT_PASS'

MODEM_HOST = '$MD_IP'
MODEM_USER = '$MD_USER'
MODEM_PASS = '$MD_PASS'
EOF

# 4. Buat Systemd Service agar bot jalan otomatis saat STB nyala
sudo cat > /etc/systemd/system/mikrobot.service <<EOF
[Unit]
Description=MikroTik Telegram Bot Service
After=network.target

[Service]
User=$USER
WorkingDirectory=$HOME/mikrobot
ExecStart=$HOME/mikrobot/venv/bin/python $HOME/mikrobot/mikro_bot.py
Restart=always

[Install]
WantedBy=multi-user.target
EOF

# 5. Aktifkan Service
sudo systemctl daemon-reload
sudo systemctl enable mikrobot.service
sudo systemctl restart mikrobot.service

echo -e "\n${GREEN}✅ INSTALASI SELESAI!${NC}"
echo -e "Bot Anda sekarang berjalan di background sebagai service."
echo -e "Gunakan command: ${GREEN}sudo systemctl status mikrobot.service${NC} untuk cek status."
